### ISSUE TITLE
Building under OSX

### ISSUE THREAD

**Issue by magnumripper** [gat3way/hashkill#12]
I spent a couple of minutes trying to understand how to build hashkill under OSX but I ended up just being confused by the general lack of opencl includes so I gave up before screwing up.

For John the Ripper, all we did to have OpenCL work for OSX was this:

1) In all places where you'd otherwise only have the else clause:

```
+ #ifdef __APPLE__
+ #include <OpenCL/opencl.h>
+ #include <OpenCL/cl_ext.h>
+ #else
  #include <CL/cl.h>
  #include <CL/cl_ext.h>
+ #endif
```

2) Add `-framework OpenCL` to LDFLAGS. No other `-I` or `-l` was needed.

This was all that was needed if my memory serves me. Do you have any ideas I could try for hashkill?

**Comment by gat3way** [comment]
I don't think it's buildable under OSX at present (CPU code contains lots of linuxisms). Otherwise, it doesn't use the OpenCL headers and doesn't link against OpenCL - instead it loads needed functions from the OpenCL library dynamically (using dlopen()/dlsym()). That eliminates the need for two builds - a CPU-only and a CPU/GPU-enabled one. It also eliminates the APP SDK build dependency.

**Comment by magnumripper** [comment]
That's a cool approach. I'll just concentrate on Linux then.
