### ISSUE TITLE
make the choice of available opencl backends configurable 

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#14]
I'm filing the bug on behalf of some lazy friend of mine, this is about kernels/compiler and the way how hashkill detects available software.
Below are more details from him:

```
if it builds support for whatever is detected on the system that's wrong
it's running amd-compiler on a box with no amd so that's kind of a hint
it needs to have a configure flag for amd/intel/nvidia and allow disable/enable
when I build on my build box it will support amd but not nvidia, that's broken
needs to enable what I tell it to, not what it feels like
and if I tell it to enable ati it needs to fail building not silently not build ati
```

Here is the mail problem (not exactly the same, but it should give an idea) in details:
http://www.gentoo.org/proj/en/qa/automagic.xml

**Comment by ZeroChaos-** [comment]
Probably could have made that a bit nicer for an official bug don't you think?

**Comment by technerd206** [comment]
poniez

**Comment by gat3way** [comment]
I think (technically speaking) that differentiation between ATI and NVidia would not be easy. However, it is quite easy to have OpenCL support a built-time configurable option. The reason is that to differentiate between ATI and NVidia, we would neet to load the OpenCL library and this (in ZeroChaos' case) would lead to segmentation fault already.

**Comment by blshkv** [comment]
Please excuse a newbie question, but shouldn't OpenCL provide some kind of an abstract layer which would ensure of portability across all video cards?  Why do you need a video card specific code? That's seems the main problem.

Users can easily symlink the /usr/lib64/libOpenCL.so library to a different OpenCL implementation at any time, that should not break the software.

**Comment by gat3way** [comment]
Yes, OpenCL was intended to run the same code on different GPUs (even CPUs and since recently FPGAs). Even though the code is portable, performance is not. Different hardware architectures have different specifics and if you want to squeeze the performance out of the card, you will soon be forced to write device-specific code. Even among AMD or NVidia you have different hardware families and that requires some changes - e.g Nvidia sm_10 hardware does not have atomic operations and has quite limited on-chip memory. Another reason for splitting AMD and NV code is that both shader compilers have bugs and thus different workarounds for them.

**Comment by blshkv** [comment]
ok, so how about (ZeroChaos please correct me if i'm wrong) if you could add two more options:
 --with-ati-ocl and --with-nvidia-ocl (even it sounds strange) to enforce an appropriate compiler only and fail if the platform is not available?

**Comment by ZeroChaos-** [comment]
if we also support --without then the default could stay the same and only users that want no automagic will be affected by the change.

**Comment by gat3way** [comment]
I think it would be more like --without-opencl as opposed to --without-xxx-ocl : because in order to enable/disable nvidia/amd support, you would have to load libOpenCL.so anyway (to get the available platforms at least). That's exactly where it crashes on ZeroChaos' system. 

Or maybe I missed the point?

**Comment by ZeroChaos-** [comment]
yes I believe you missed the point, this is bug #14 not bug #13

**Comment by gat3way** [comment]
OK, so --without-amd-ocl and --without-nv-ocl  would (I guess) suffice?

**Comment by ZeroChaos-** [comment]
I would say like this:

--with-amd-ocl skip testing and assume building with amd-ocl
--with-nv-ocl skip testing and assume building with nv-ocl
--without-amd-ocl skip testing and assume not using amd-ocl
--without-nv-ocl skip testing and assume not using nv-ocl

That would suffice, until you support the intel-ocl-sdk (which you may want to consider)

**Comment by gat3way** [comment]
Yes, that is planned (when eventually PHI comes out and I get one :) which will happen no earlier than Q1 2013 anyway). That's why I am not quite happy about those (--with-something disabling all the others) as you might want to have both PHI and NV support for example.

**Comment by gat3way** [comment]
Otherwise, intel opencl support is just slow on CPUs (well written intrinsics code being much faster).

**Comment by ZeroChaos-** [comment]
I never said that the flags should be mutually exclusive.  My build system has ati hardware only, but my livecd users could have either ati or nvidia or both.

**Comment by gat3way** [comment]
OK, I will implement both --with-\* and --without-\* (worst case: just --without ones which I hope would also be sufficient, though less convinient). This however is my #2 priority on the list, I am now working on the truecrypt stuff where I am at ~40% (RIPEMD160/WHIRLPOOL/SHA512 already implemented on GPUs, AES/Twofish/Serpent already done on CPU). Need to implement XTS and LRW encryption modes as well as PBKDF2 using the already available RIPEMD160 and WHIRLPOOL hash algos and finally integrate that all into a truecrypt plugin. I expect it to take ~1-2 weeks (hopefully less than that).

**Comment by gat3way** [comment]
Added --enable-amd-ocl, --enable-nv-ocl (default) and respectively, --disable-\* with commit dd12fb35d0da17ecece739ae842a26736dfc54b6

Default behavior is to _BUILD_ all kernels, you may explicitly disable those.

If you have any trouble with those, please reopen the ticket.
