### ISSUE TITLE
android brute force 

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#15]
Would you be interested to add support for Android?

Here is more details:
https://santoku-linux.com/howto/mobile-forensics/how-to-brute-force-android-encryption
https://github.com/santoku/Santoku-Linux/tree/master/tools/android

The tool is limited to PIN brute force only and it's not a big deal.
However, a proper password brute force would be very much useful.

I guess it should not be very difficult to do since all documentation is available.
http://source.android.com/tech/encryption/android_crypto_implementation.html
http://code.google.com/p/cyanogenmod/issues/detail?id=5678

**Comment by gat3way** [comment]
Since Android's FDE is based on dmcrypt/luks, using AES-128 and cbc-essiv-sha256, it should already be supported by the luks plugin. However, it has never been tested against Android encrypted device. I don't even clearly know how to acquire that (thanks for the link). Unfortunately, I don't have the opportunity to test right now :( I have an old Wildfire which does not support FDE and my wife has a Galaxy S3 which supports that but it broke several days ago :( Any example image (with password to validate) would be very useful. Alternatively, you could try it yourself, you should be using the luks plugin and some rule file that is suited to cracking that.

**Comment by gat3way** [comment]
BTW they turned out different. Android FDE support is already in hashkill since several days ago.

**Comment by blshkv** [comment]
Thanks, in Pentoo now ;-)
https://code.google.com/p/pentoo/source/detail?r=4552
