### ISSUE TITLE
hashkill errors on /dev/nvidiactl with nvidia support

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#32]
I need you help here. Nvidia users unable to compile hashkill under Gentoo.
It might be something to do with a sandbox env during compilation or something deeper.
Could you have a look at the build log please:

https://code.google.com/p/pentoo/issues/detail?id=128

Thank you.

**Comment by gat3way** [comment]
Hello,

hashkill does not directly access /dev/nvidiactl , I guess the OpenCL library is what interacts with nvidia device nodes, but it is out of our control. Nevertheless I think that if hashkill has no permissions to write to that device, opencl calls fail too, because I've seen similar issues with AMD in the past (OpenCL fails to use the device if /dev/ati/cardX is not readable/writable by the user even though hashkill never directly accesses that).

Anyway, I don't think there is much that can be done on hashkill's side about this unfortunately.

**Comment by blshkv** [comment]
Thanks, I found some workarounds and will try to fix the ebuild.

**Comment by blshkv** [comment]
Hi, it seems that user has not configured OpenCL properly. Could you verify and add an error code:
 -1001  CL_PLATFORM_NOT_FOUND_KHR in ocl-base.c file?

**Comment by gat3way** [comment]
Added with latest commit. Closing the issue.
