### ISSUE TITLE
hashkill should support multithreading (all cores) compilation

### ISSUE THREAD

**Issue by blshkv** [gat3way/hashkill#33]
Modern CPUs has 4 and more cores. People with 32 cores find it PAINFULLY slow
to compile with a single thread.

Please add multithreading support.

**Comment by ZeroChaos-** [comment]
watching hashkill build ati kernels and htop reports 1 cpu in use.

**Comment by gat3way** [comment]
Working on it

**Comment by ZeroChaos-** [comment]
That's why we like you ;-)

**Comment by gat3way** [comment]
Does the latest commit work for you? You should be able to build kernels in parallel now using make -jX.

Not well tested here though...yet

**Comment by ZeroChaos-** [comment]
works for a while, seems to slow down hard right here:

building for Barts
building for Cayman
/bin/sh: line 2: 27800 Segmentation fault      ./amd-compiler amd_oracle_old n
make[2]: **\* [amd_oracle_old] Error 139
building for Juniper
building for Barts
building for Loveland
building for Redwood

Compiling amd_sha512_long with SINGLE_MODE...
building for ATI RV770
building for Cayman

Granted there was a segfault there, but around that point it started building with 2 threads instead of 32.

**Comment by ZeroChaos-** [comment]
it might be because that is right near the end and it simply didn't have anything left to build.  it seemed to finish really soon after.

**Comment by ZeroChaos-** [comment]
I believe you can safely close this bug at this time.  Everything is looking very good for the multi-threading.  Other issues appear unrelated to that and I'll open a new bug.

**Comment by gat3way** [comment]
This:
/bin/sh: line 2: 27800 Segmentation fault ./amd-compiler amd_oracle_old n
make[2]: **\* [amd_oracle_old] Error 139

Is very likely a bug in the OpenCL runtime. It occurs with some Catalyst versions. I cannot give a good solution to that other than updating the driver with a newer version

Closing the issue. We can open a separate one for the segfault.
