### ISSUE TITLE
sandbox errors

### ISSUE THREAD

**Issue by ZeroChaos-** [gat3way/hashkill#34]
For safety and security gentoo builds everything inside of a sandbox (you can only write to your own dir) and with user privledges.

hashkill attempt to violate this constantly trying to touch things in /dev.  Can you please provide details on what if any of this is actually needed and why?

(trimmed out duplicates best as I could)

VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: __xmknod
S: deny
P: /dev/nvidiactl
A: /dev/nvidiactl
R: /dev/nvidiactl
C: ./amd-compiler amd_md5_long ns 

F: chmod
S: deny
P: /dev/nvidiactl
A: /dev/nvidiactl
R: /dev/nvidiactl
C: ./amd-compiler amd_md5_long ns 

F: chown
S: deny
P: /dev/nvidiactl
A: /dev/nvidiactl
R: /dev/nvidiactl
C: ./amd-compiler amd_md5_long ns 

F: open_wr
S: deny
P: /etc/ati/amdpcsdb
A: /etc/ati/amdpcsdb
R: /etc/ati/amdpcsdb
C: ./amd-compiler amd_sha1_passsaltu n 

F: open_wr./amd-compiler amd_sha1_passsalt_long n open_wr

S: 
S: denydeny
P: 
P: /etc/ati/amdpcsdb/etc/ati/amdpcsdb
A: 
A: /etc/ati/amdpcsdb/etc/ati/amdpcsdb
R: 
R: /etc/ati/amdpcsdb/etc/ati/amdpcsdb
C: 
C: ./amd-compiler amd_ipb2_long n ./amd-compiler amd_ipb2 n 

Some of this is just plain powerfully bad.  Nothing during build should need to be opening files inside of /etc for write, that's just plain wrong.  Some of this is possibly legit, like needing access to /dev/nvidiactl for instance, but I need an explanation if possible on what is going on and why it needs to do it.  Talking to the hardware directly to figure out what to build isn't always wrong, but in situations where someone is trying to build a binary for other users it is wrong as it will support the build system hardware not the target system hardware.

**Comment by gat3way** [comment]
Unfortunately none of this is under hashkill's control - you can confirm that by grepping for those files in the source. Hashkill never touches them. I believe though the OpenCL library does that instead and we need to load the library in order to compile kernels. I am thinking about some workaround, but frankly at that point I can't think of any (other than providing the sources precompiled which has lots of disadvantages).

**Comment by ZeroChaos-** [comment]
Any idea why /dev/nvidiactl and /dev/ati need to be written to during compilation?  cryptohaze-multiforcer (for instance) doesn't appear to have this issue.

**Comment by gat3way** [comment]
I guess Bitweasil does not compile kernels in build-time, instead he compiles them from source in runtime, thus nvidiactrl is not being accessed at build-time. Hashkill's kernel compiler is just a wrapper around OpenCL's clBuildProgram(). I am trying to think of another program that does the same as hashkill, but I can't think of any at the moment. hashcat comes close, but since their kernels are closed-source, you get them already precompiled (in PTX/IR form). 

At that point, the only thing that can be done is either to ship the prebuilt kernels instead of compiling them during build....or compile them in runtime rather than build-time (which can have a severe performance impact with larger kernels, though it can be mitigated by caching results). Unfortunately both approaches are a big-time efforts and they have drawbacks too.

**Comment by gat3way** [comment]
Well shipping precompiled kernels is not a big time effort, but it defeats the point of hashkill being opensource. I do ship prebuilt binaries separately, but people that want to build from source won't be happy if I give them binary blobs :(

**Comment by ZeroChaos-** [comment]
I'll try to be a bit more permissive about what I allow.  Obviously I'm NOT going to allow building to rewrite config files, but I can allow it to talk to the hardware and see what happens.  Of course it's a bit funny since my build box will build for ati and nvidia but doesn't have an nvidia card at all....

Let me test and see what happens

**Comment by ZeroChaos-** [comment]
looks like adding write permissions to these is enough to make it mostly happy:

 /dev/nvidia0
 /dev/nvidiactl
 /dev/ati

For now I'll call this okay I think, at least as far as the sandboxing issues.
