### ISSUE TITLE
nvidia build attempt to access /dev/ati and vice versa

### ISSUE THREAD

**Issue by ZeroChaos-** [gat3way/hashkill#35]
I configure like this:

./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --disable-dependency-tracking --enable-nv-ocl --disable-amd-ocl

Then I run make and it tries to access /dev/ati pretty hard:

Compiling nvidia_mysql5 without flags...
- ACCESS DENIED:  open_wr:      /dev/ati/card0

Compiling nvidia_sha1_passsaltu without flags...

Compiling nvidia_sha1_passsalt_long without flags...

Compiling nvidia_sha1_passsalt without flags...

Compiling nvidia_sha1_passsaltul_long without flags...

Compiling nvidia_vbulletin without flags...
- ACCESS DENIED:  open_wr:      /dev/ati/card0

Compiling nvidia_oracle_old_long without flags...

Compiling nvidia_sha1_passsaltu_long without flags...

Compiling nvidia_vbulletin_long without flags...
Unable to open ../nvidia_sha1_passsaltul_long.cl. Exiting.

Compiling nvidia_mysql5_long without flags...

Compiling nvidia_md5_saltpass without flags...
- ACCESS DENIED:  open_wr:      /dev/ati/card0
- ACCESS DENIED:  open_wr:      /dev/ati/card0

Compiling nvidia_oracle_old without flags...
- ACCESS DENIED:  open_wr:      /dev/ati/card0
- ACCESS DENIED:  open_wr:      /dev/ati/card0

(there is a LOT more like that)

Is there a way to prevent it from doing this?  I told it to build for only nvidia and it's going crazy trying to hit /dev/ati/card0.  Granted, I only actually have an ati card on my system, but that doesn't change the fact that I told it to build for nvidia only and that's what I expect.

Building for ati only isn't nearly as bad (doesn't try to write to anything in /dev) but it does spam the hell out of dmesg with this:

[429256.877799] NVRM: No NVIDIA graphics adapter found!

Can we more forcefully set the build parameters?  It is optional to build support for one or the other but it keeps looking for the disabled choice anyway...

**Comment by gat3way** [comment]
The API does not have means to explicitly choose the nvidia platform. So in order to use a NV one, I have to do the following sequence:

1) Call clGetPlatformIDs() to get an array of pointers to platform handlers
2) For each of the elements of that array, call clGetPlatformInfo() with CL_PLATFORM_VENDOR command to obtain the vendor string
3) Compare string with "NVIDIA" to ensure that is the NV platform.

We can of course break from the loop once NVIDIA platform is found, yet it's not guaranteed that the nvidia platform will be "before" the AMD one.

OpenCL does not define a way to directly get a handler to the NVIDIA platform rather than getting all platforms and check if any of them is a NV one...at that point. 

As a result, clGetPlatformInfo() can be called against the AMD platform which probably makes the OpenCL lib access the ati device.

**Comment by ZeroChaos-** [comment]
That's fine.  It's just a change in our methodology of allows.  If that's how it is then we deal with it. thanks for the explanation.
